name: Rust CI & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build and Test
        run: cargo build --verbose && cargo test --verbose

      - name: Install nightly toolchain for coverage
        run: |
          rustup toolchain install nightly
          rustup component add llvm-tools-preview --toolchain nightly
          rustup component add --toolchain nightly rustfmt
          rustup component add --toolchain nightly clippy

      - name: Generate Coverage Report (LCOV)
        run: cargo +nightly llvm-cov --all-features --workspace --doctests --lcov --output-path lcov.info

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: lcov.info
